version: '3.2' # specify docker-compose version
 
# Define the services/ containers to be run
services:
  angular: # name of the first service
    image: node
    ports:
      - "4200:4200" # specify port mapping
    volumes:
      - ${PWD}:/app
    command: /bin/sh -c "cd /app && npm install && npm start"
 
  express: # name of the second service
    image: node
    ports:
      - "3000:3000" #specify ports mapping
    volumes:
      - ${PWD}:/app
    command:  /bin/sh -c "cd /app && npm install && npm start"

    links:
      - database # link this service to the database service
 
  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
    - "27017:27017" # specify port forwarding