version: '3.0' # specify docker-compose version
 
# Define the services/ containers to be run
services:
  angular: # name of the first service
    build: # specify the directory of the Dockerfile
      context: .
      dockerfile: Dockerfile-front
    ports:
    - "4200:4200" # specify port mapping
 
  express: # name of the second service
    build: # specify the directory of the Dockerfile
      context: .
      dockerfile: Dockerfile-back
    ports:
    - "3000:3000" #specify ports mapping
    links:
    - database # link this service to the database service
 
  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
    - "27017:27017" # specify port forwarding